language: go
go:
  - "1.11"
install:
  - go get -v -t ./...
before_script:
  - go test -v ./...
script:
  - find . -maxdepth 1 -type d \( ! -name . ! -name .git \) -exec bash -c 'cd {} && make bench' \;
jobs:
  fast_finish: true
notifications:
  email:
    on_success: change
    on_failure: always
